// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub_to_agent.proto

package idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpgradePrimariesRequest struct {
	SourceBinDir         string         `protobuf:"bytes,1,opt,name=SourceBinDir" json:"SourceBinDir,omitempty"`
	TargetBinDir         string         `protobuf:"bytes,2,opt,name=TargetBinDir" json:"TargetBinDir,omitempty"`
	TargetVersion        string         `protobuf:"bytes,3,opt,name=TargetVersion" json:"TargetVersion,omitempty"`
	DataDirPairs         []*DataDirPair `protobuf:"bytes,4,rep,name=DataDirPairs" json:"DataDirPairs,omitempty"`
	CheckOnly            bool           `protobuf:"varint,5,opt,name=CheckOnly" json:"CheckOnly,omitempty"`
	UseLinkMode          bool           `protobuf:"varint,6,opt,name=UseLinkMode" json:"UseLinkMode,omitempty"`
	MasterBackupDir      string         `protobuf:"bytes,7,opt,name=MasterBackupDir" json:"MasterBackupDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpgradePrimariesRequest) Reset()         { *m = UpgradePrimariesRequest{} }
func (m *UpgradePrimariesRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesRequest) ProtoMessage()    {}
func (*UpgradePrimariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{0}
}
func (m *UpgradePrimariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesRequest.Unmarshal(m, b)
}
func (m *UpgradePrimariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradePrimariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesRequest.Merge(dst, src)
}
func (m *UpgradePrimariesRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesRequest.Size(m)
}
func (m *UpgradePrimariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesRequest proto.InternalMessageInfo

func (m *UpgradePrimariesRequest) GetSourceBinDir() string {
	if m != nil {
		return m.SourceBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetTargetBinDir() string {
	if m != nil {
		return m.TargetBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetTargetVersion() string {
	if m != nil {
		return m.TargetVersion
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetDataDirPairs() []*DataDirPair {
	if m != nil {
		return m.DataDirPairs
	}
	return nil
}

func (m *UpgradePrimariesRequest) GetCheckOnly() bool {
	if m != nil {
		return m.CheckOnly
	}
	return false
}

func (m *UpgradePrimariesRequest) GetUseLinkMode() bool {
	if m != nil {
		return m.UseLinkMode
	}
	return false
}

func (m *UpgradePrimariesRequest) GetMasterBackupDir() string {
	if m != nil {
		return m.MasterBackupDir
	}
	return ""
}

type DataDirPair struct {
	SourceDataDir        string   `protobuf:"bytes,1,opt,name=SourceDataDir" json:"SourceDataDir,omitempty"`
	TargetDataDir        string   `protobuf:"bytes,2,opt,name=TargetDataDir" json:"TargetDataDir,omitempty"`
	SourcePort           int32    `protobuf:"varint,3,opt,name=SourcePort" json:"SourcePort,omitempty"`
	TargetPort           int32    `protobuf:"varint,4,opt,name=TargetPort" json:"TargetPort,omitempty"`
	Content              int32    `protobuf:"varint,5,opt,name=Content" json:"Content,omitempty"`
	DBID                 int32    `protobuf:"varint,6,opt,name=DBID" json:"DBID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDirPair) Reset()         { *m = DataDirPair{} }
func (m *DataDirPair) String() string { return proto.CompactTextString(m) }
func (*DataDirPair) ProtoMessage()    {}
func (*DataDirPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{1}
}
func (m *DataDirPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDirPair.Unmarshal(m, b)
}
func (m *DataDirPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDirPair.Marshal(b, m, deterministic)
}
func (dst *DataDirPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDirPair.Merge(dst, src)
}
func (m *DataDirPair) XXX_Size() int {
	return xxx_messageInfo_DataDirPair.Size(m)
}
func (m *DataDirPair) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDirPair.DiscardUnknown(m)
}

var xxx_messageInfo_DataDirPair proto.InternalMessageInfo

func (m *DataDirPair) GetSourceDataDir() string {
	if m != nil {
		return m.SourceDataDir
	}
	return ""
}

func (m *DataDirPair) GetTargetDataDir() string {
	if m != nil {
		return m.TargetDataDir
	}
	return ""
}

func (m *DataDirPair) GetSourcePort() int32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}

func (m *DataDirPair) GetTargetPort() int32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func (m *DataDirPair) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

func (m *DataDirPair) GetDBID() int32 {
	if m != nil {
		return m.DBID
	}
	return 0
}

type UpgradePrimariesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradePrimariesReply) Reset()         { *m = UpgradePrimariesReply{} }
func (m *UpgradePrimariesReply) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesReply) ProtoMessage()    {}
func (*UpgradePrimariesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{2}
}
func (m *UpgradePrimariesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesReply.Unmarshal(m, b)
}
func (m *UpgradePrimariesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesReply.Marshal(b, m, deterministic)
}
func (dst *UpgradePrimariesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesReply.Merge(dst, src)
}
func (m *UpgradePrimariesReply) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesReply.Size(m)
}
func (m *UpgradePrimariesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesReply proto.InternalMessageInfo

type CreateSegmentDataDirRequest struct {
	Datadirs             []string `protobuf:"bytes,1,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirRequest) Reset()         { *m = CreateSegmentDataDirRequest{} }
func (m *CreateSegmentDataDirRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirRequest) ProtoMessage()    {}
func (*CreateSegmentDataDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{3}
}
func (m *CreateSegmentDataDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSegmentDataDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirRequest.Merge(dst, src)
}
func (m *CreateSegmentDataDirRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Size(m)
}
func (m *CreateSegmentDataDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirRequest proto.InternalMessageInfo

func (m *CreateSegmentDataDirRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CreateSegmentDataDirReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirReply) Reset()         { *m = CreateSegmentDataDirReply{} }
func (m *CreateSegmentDataDirReply) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirReply) ProtoMessage()    {}
func (*CreateSegmentDataDirReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{4}
}
func (m *CreateSegmentDataDirReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirReply.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirReply.Marshal(b, m, deterministic)
}
func (dst *CreateSegmentDataDirReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirReply.Merge(dst, src)
}
func (m *CreateSegmentDataDirReply) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirReply.Size(m)
}
func (m *CreateSegmentDataDirReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirReply proto.InternalMessageInfo

type StopAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentRequest) Reset()         { *m = StopAgentRequest{} }
func (m *StopAgentRequest) String() string { return proto.CompactTextString(m) }
func (*StopAgentRequest) ProtoMessage()    {}
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{5}
}
func (m *StopAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentRequest.Unmarshal(m, b)
}
func (m *StopAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentRequest.Marshal(b, m, deterministic)
}
func (dst *StopAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentRequest.Merge(dst, src)
}
func (m *StopAgentRequest) XXX_Size() int {
	return xxx_messageInfo_StopAgentRequest.Size(m)
}
func (m *StopAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentRequest proto.InternalMessageInfo

type StopAgentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentReply) Reset()         { *m = StopAgentReply{} }
func (m *StopAgentReply) String() string { return proto.CompactTextString(m) }
func (*StopAgentReply) ProtoMessage()    {}
func (*StopAgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{6}
}
func (m *StopAgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentReply.Unmarshal(m, b)
}
func (m *StopAgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentReply.Marshal(b, m, deterministic)
}
func (dst *StopAgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentReply.Merge(dst, src)
}
func (m *StopAgentReply) XXX_Size() int {
	return xxx_messageInfo_StopAgentReply.Size(m)
}
func (m *StopAgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentReply proto.InternalMessageInfo

type CheckSegmentDiskSpaceRequest struct {
	Request              *CheckDiskSpaceRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Datadirs             []string               `protobuf:"bytes,2,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CheckSegmentDiskSpaceRequest) Reset()         { *m = CheckSegmentDiskSpaceRequest{} }
func (m *CheckSegmentDiskSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckSegmentDiskSpaceRequest) ProtoMessage()    {}
func (*CheckSegmentDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{7}
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Unmarshal(m, b)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Marshal(b, m, deterministic)
}
func (dst *CheckSegmentDiskSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSegmentDiskSpaceRequest.Merge(dst, src)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Size(m)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSegmentDiskSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSegmentDiskSpaceRequest proto.InternalMessageInfo

func (m *CheckSegmentDiskSpaceRequest) GetRequest() *CheckDiskSpaceRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CheckSegmentDiskSpaceRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type UpdateRecoveryConfsRequest struct {
	RecoveryConfInfos    []*RecoveryConfInfo `protobuf:"bytes,1,rep,name=RecoveryConfInfos" json:"RecoveryConfInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateRecoveryConfsRequest) Reset()         { *m = UpdateRecoveryConfsRequest{} }
func (m *UpdateRecoveryConfsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecoveryConfsRequest) ProtoMessage()    {}
func (*UpdateRecoveryConfsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{8}
}
func (m *UpdateRecoveryConfsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecoveryConfsRequest.Unmarshal(m, b)
}
func (m *UpdateRecoveryConfsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecoveryConfsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRecoveryConfsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecoveryConfsRequest.Merge(dst, src)
}
func (m *UpdateRecoveryConfsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecoveryConfsRequest.Size(m)
}
func (m *UpdateRecoveryConfsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecoveryConfsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecoveryConfsRequest proto.InternalMessageInfo

func (m *UpdateRecoveryConfsRequest) GetRecoveryConfInfos() []*RecoveryConfInfo {
	if m != nil {
		return m.RecoveryConfInfos
	}
	return nil
}

type UpdateRecoveryConfsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecoveryConfsReply) Reset()         { *m = UpdateRecoveryConfsReply{} }
func (m *UpdateRecoveryConfsReply) String() string { return proto.CompactTextString(m) }
func (*UpdateRecoveryConfsReply) ProtoMessage()    {}
func (*UpdateRecoveryConfsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{9}
}
func (m *UpdateRecoveryConfsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecoveryConfsReply.Unmarshal(m, b)
}
func (m *UpdateRecoveryConfsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecoveryConfsReply.Marshal(b, m, deterministic)
}
func (dst *UpdateRecoveryConfsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecoveryConfsReply.Merge(dst, src)
}
func (m *UpdateRecoveryConfsReply) XXX_Size() int {
	return xxx_messageInfo_UpdateRecoveryConfsReply.Size(m)
}
func (m *UpdateRecoveryConfsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecoveryConfsReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecoveryConfsReply proto.InternalMessageInfo

type RecoveryConfInfo struct {
	TargetPrimaryPort    int32    `protobuf:"varint,1,opt,name=TargetPrimaryPort" json:"TargetPrimaryPort,omitempty"`
	SourcePrimaryPort    int32    `protobuf:"varint,2,opt,name=SourcePrimaryPort" json:"SourcePrimaryPort,omitempty"`
	TargetMirrorDataDir  string   `protobuf:"bytes,3,opt,name=TargetMirrorDataDir" json:"TargetMirrorDataDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoveryConfInfo) Reset()         { *m = RecoveryConfInfo{} }
func (m *RecoveryConfInfo) String() string { return proto.CompactTextString(m) }
func (*RecoveryConfInfo) ProtoMessage()    {}
func (*RecoveryConfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_afba379c2dbdfc71, []int{10}
}
func (m *RecoveryConfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoveryConfInfo.Unmarshal(m, b)
}
func (m *RecoveryConfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoveryConfInfo.Marshal(b, m, deterministic)
}
func (dst *RecoveryConfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoveryConfInfo.Merge(dst, src)
}
func (m *RecoveryConfInfo) XXX_Size() int {
	return xxx_messageInfo_RecoveryConfInfo.Size(m)
}
func (m *RecoveryConfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoveryConfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RecoveryConfInfo proto.InternalMessageInfo

func (m *RecoveryConfInfo) GetTargetPrimaryPort() int32 {
	if m != nil {
		return m.TargetPrimaryPort
	}
	return 0
}

func (m *RecoveryConfInfo) GetSourcePrimaryPort() int32 {
	if m != nil {
		return m.SourcePrimaryPort
	}
	return 0
}

func (m *RecoveryConfInfo) GetTargetMirrorDataDir() string {
	if m != nil {
		return m.TargetMirrorDataDir
	}
	return ""
}

func init() {
	proto.RegisterType((*UpgradePrimariesRequest)(nil), "idl.UpgradePrimariesRequest")
	proto.RegisterType((*DataDirPair)(nil), "idl.DataDirPair")
	proto.RegisterType((*UpgradePrimariesReply)(nil), "idl.UpgradePrimariesReply")
	proto.RegisterType((*CreateSegmentDataDirRequest)(nil), "idl.CreateSegmentDataDirRequest")
	proto.RegisterType((*CreateSegmentDataDirReply)(nil), "idl.CreateSegmentDataDirReply")
	proto.RegisterType((*StopAgentRequest)(nil), "idl.StopAgentRequest")
	proto.RegisterType((*StopAgentReply)(nil), "idl.StopAgentReply")
	proto.RegisterType((*CheckSegmentDiskSpaceRequest)(nil), "idl.CheckSegmentDiskSpaceRequest")
	proto.RegisterType((*UpdateRecoveryConfsRequest)(nil), "idl.UpdateRecoveryConfsRequest")
	proto.RegisterType((*UpdateRecoveryConfsReply)(nil), "idl.UpdateRecoveryConfsReply")
	proto.RegisterType((*RecoveryConfInfo)(nil), "idl.RecoveryConfInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Agent service

type AgentClient interface {
	CheckDiskSpace(ctx context.Context, in *CheckSegmentDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	UpgradePrimaries(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error)
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error)
	UpdateRecoveryConfs(ctx context.Context, in *UpdateRecoveryConfsRequest, opts ...grpc.CallOption) (*UpdateRecoveryConfsReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CheckDiskSpace(ctx context.Context, in *CheckSegmentDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CheckDiskSpace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpgradePrimaries(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error) {
	out := new(UpgradePrimariesReply)
	err := grpc.Invoke(ctx, "/idl.Agent/UpgradePrimaries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error) {
	out := new(CreateSegmentDataDirReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CreateSegmentDataDirectories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error) {
	out := new(StopAgentReply)
	err := grpc.Invoke(ctx, "/idl.Agent/StopAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpdateRecoveryConfs(ctx context.Context, in *UpdateRecoveryConfsRequest, opts ...grpc.CallOption) (*UpdateRecoveryConfsReply, error) {
	out := new(UpdateRecoveryConfsReply)
	err := grpc.Invoke(ctx, "/idl.Agent/UpdateRecoveryConfs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	CheckDiskSpace(context.Context, *CheckSegmentDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	UpgradePrimaries(context.Context, *UpgradePrimariesRequest) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(context.Context, *CreateSegmentDataDirRequest) (*CreateSegmentDataDirReply, error)
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentReply, error)
	UpdateRecoveryConfs(context.Context, *UpdateRecoveryConfsRequest) (*UpdateRecoveryConfsReply, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSegmentDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckDiskSpace(ctx, req.(*CheckSegmentDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpgradePrimaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePrimariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpgradePrimaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/UpgradePrimaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpgradePrimaries(ctx, req.(*UpgradePrimariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateSegmentDataDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CreateSegmentDataDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, req.(*CreateSegmentDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/StopAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpdateRecoveryConfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecoveryConfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpdateRecoveryConfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/UpdateRecoveryConfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpdateRecoveryConfs(ctx, req.(*UpdateRecoveryConfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDiskSpace",
			Handler:    _Agent_CheckDiskSpace_Handler,
		},
		{
			MethodName: "UpgradePrimaries",
			Handler:    _Agent_UpgradePrimaries_Handler,
		},
		{
			MethodName: "CreateSegmentDataDirectories",
			Handler:    _Agent_CreateSegmentDataDirectories_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _Agent_StopAgent_Handler,
		},
		{
			MethodName: "UpdateRecoveryConfs",
			Handler:    _Agent_UpdateRecoveryConfs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub_to_agent.proto",
}

func init() { proto.RegisterFile("hub_to_agent.proto", fileDescriptor_hub_to_agent_afba379c2dbdfc71) }

var fileDescriptor_hub_to_agent_afba379c2dbdfc71 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0xfd, 0x02, 0xa5, 0x2d, 0x97, 0x7e, 0x5d, 0x6a, 0x54, 0x35, 0x4b, 0x59, 0x97, 0x45, 0x7b,
	0xe0, 0x61, 0x42, 0x13, 0xeb, 0x4b, 0x1f, 0x07, 0xbc, 0x54, 0x1a, 0x2b, 0x0a, 0x63, 0x7b, 0xac,
	0x4c, 0xe2, 0x82, 0x05, 0x8d, 0x33, 0xc7, 0x4c, 0xe2, 0xdf, 0xf4, 0x6d, 0x3f, 0x65, 0x7f, 0x6b,
	0xb2, 0x9d, 0x40, 0x12, 0x92, 0xbd, 0xe1, 0x73, 0xce, 0xbd, 0xf6, 0xbd, 0xe7, 0x10, 0x40, 0xcb,
	0xcd, 0xfc, 0x51, 0xb0, 0x47, 0xbc, 0x20, 0xa1, 0xe8, 0x45, 0x9c, 0x09, 0x86, 0xea, 0x34, 0x58,
	0xdb, 0xa6, 0xbf, 0xa6, 0x92, 0x58, 0x6e, 0xe6, 0x1a, 0x76, 0x7f, 0xd7, 0xe0, 0x6a, 0x16, 0x2d,
	0x38, 0x0e, 0xc8, 0x84, 0xd3, 0x67, 0xcc, 0x29, 0x89, 0x3d, 0xf2, 0x73, 0x43, 0x62, 0x81, 0x5c,
	0x38, 0x9b, 0xb2, 0x0d, 0xf7, 0xc9, 0x80, 0x86, 0x23, 0xca, 0x2d, 0xc3, 0x31, 0xba, 0x4d, 0x2f,
	0x87, 0x49, 0xcd, 0x37, 0xcc, 0x17, 0x44, 0x24, 0x9a, 0x9a, 0xd6, 0x64, 0x31, 0xf4, 0x1e, 0xfe,
	0xd7, 0xe7, 0xef, 0x84, 0xc7, 0x94, 0x85, 0x56, 0x5d, 0x89, 0xf2, 0x20, 0xba, 0x85, 0xb3, 0x11,
	0x16, 0x78, 0x44, 0xf9, 0x04, 0x53, 0x1e, 0x5b, 0x47, 0x4e, 0xbd, 0xdb, 0xea, 0x9b, 0x3d, 0x1a,
	0xac, 0x7b, 0x19, 0xc2, 0xcb, 0xa9, 0x50, 0x07, 0x9a, 0xc3, 0x25, 0xf1, 0x57, 0x0f, 0xe1, 0x7a,
	0x6b, 0x35, 0x1c, 0xa3, 0x7b, 0xea, 0xed, 0x01, 0xe4, 0x40, 0x6b, 0x16, 0x93, 0x2f, 0x34, 0x5c,
	0x8d, 0x59, 0x40, 0xac, 0x63, 0xc5, 0x67, 0x21, 0xd4, 0x85, 0x57, 0x63, 0x1c, 0x0b, 0xc2, 0x07,
	0xd8, 0x5f, 0x6d, 0x22, 0x39, 0xc2, 0x89, 0x7a, 0x5d, 0x11, 0x76, 0xff, 0x18, 0xd0, 0xca, 0x5c,
	0x2d, 0xa7, 0xd2, 0x9b, 0x48, 0xc0, 0x64, 0x3d, 0x79, 0x70, 0x3f, 0x7b, 0xaa, 0xaa, 0x65, 0x67,
	0x4f, 0x55, 0x37, 0x00, 0xba, 0x6c, 0xc2, 0xb8, 0x50, 0xeb, 0x69, 0x78, 0x19, 0x44, 0xf2, 0xba,
	0x40, 0xf1, 0x47, 0x9a, 0xdf, 0x23, 0xc8, 0x82, 0x93, 0x21, 0x0b, 0x05, 0x09, 0x85, 0xda, 0x41,
	0xc3, 0x4b, 0x8f, 0x08, 0xc1, 0xd1, 0x68, 0x70, 0x3f, 0x52, 0xa3, 0x37, 0x3c, 0xf5, 0xdb, 0xbd,
	0x82, 0xcb, 0x43, 0xcb, 0xa3, 0xf5, 0xd6, 0xbd, 0x83, 0xeb, 0x21, 0x27, 0x58, 0x90, 0x29, 0x59,
	0x3c, 0x93, 0x30, 0x7d, 0x5e, 0x9a, 0x07, 0x1b, 0x4e, 0x03, 0x2c, 0x70, 0x20, 0xdd, 0x31, 0x9c,
	0x7a, 0xb7, 0xe9, 0xed, 0xce, 0xee, 0x35, 0xbc, 0x2e, 0x2f, 0x95, 0x7d, 0x11, 0x98, 0x53, 0xc1,
	0xa2, 0xcf, 0x32, 0x8e, 0x49, 0x33, 0xd7, 0x84, 0xf3, 0x0c, 0x26, 0x55, 0x11, 0x74, 0x94, 0x73,
	0x69, 0x07, 0x1a, 0xaf, 0xa6, 0x11, 0xf6, 0x49, 0x7a, 0xfd, 0x2d, 0x9c, 0x70, 0xfd, 0x53, 0xad,
	0xba, 0xd5, 0xb7, 0x55, 0x36, 0x54, 0x4d, 0x51, 0xec, 0xa5, 0xd2, 0xdc, 0xa3, 0x6b, 0x85, 0x47,
	0x63, 0xb0, 0x67, 0x51, 0x80, 0x05, 0xf1, 0x88, 0xcf, 0x7e, 0x11, 0xbe, 0x1d, 0xb2, 0xf0, 0x69,
	0x17, 0xff, 0x21, 0x5c, 0x64, 0xf1, 0xfb, 0xf0, 0x89, 0xe9, 0xb9, 0x5b, 0xfd, 0x4b, 0x75, 0x73,
	0x91, 0xf5, 0x0e, 0xf5, 0xae, 0x0d, 0x56, 0xe9, 0x15, 0x72, 0xe0, 0x17, 0x03, 0xcc, 0x62, 0x05,
	0xfa, 0x00, 0x17, 0x89, 0xb1, 0xca, 0x9b, 0xad, 0x72, 0xdc, 0x50, 0xee, 0x1d, 0x12, 0x52, 0x9d,
	0xc4, 0x24, 0xa3, 0xae, 0x69, 0xf5, 0x01, 0x81, 0x3e, 0x42, 0x5b, 0xb7, 0x18, 0x53, 0xce, 0x19,
	0x4f, 0x23, 0xa9, 0xff, 0x8e, 0x65, 0x54, 0xff, 0xa5, 0x0e, 0x0d, 0x65, 0x11, 0x7a, 0x80, 0xf3,
	0xfc, 0xa6, 0xd1, 0xbb, 0xfd, 0xfa, 0x2b, 0x2c, 0xb3, 0xad, 0x52, 0x87, 0xe4, 0xec, 0xff, 0xa1,
	0xaf, 0x60, 0x16, 0x53, 0x88, 0x3a, 0x4a, 0x5f, 0xf1, 0x3d, 0xb2, 0xed, 0x0a, 0x56, 0xf7, 0x9b,
	0x43, 0xa7, 0x2c, 0x81, 0xc4, 0x17, 0x4c, 0xf5, 0x76, 0xf4, 0x5b, 0xaa, 0xf3, 0x6d, 0xdf, 0xfc,
	0x43, 0xa1, 0xef, 0xb8, 0x83, 0xe6, 0x2e, 0xb4, 0x48, 0x87, 0xa0, 0x18, 0x6c, 0xbb, 0x5d, 0x84,
	0x75, 0xe9, 0x0f, 0x68, 0x97, 0x04, 0x01, 0xbd, 0x4d, 0x66, 0xaa, 0x4a, 0xa1, 0xfd, 0xa6, 0x5a,
	0xa0, 0x1a, 0xcf, 0x8f, 0xd5, 0x87, 0xfc, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x05,
	0x33, 0x15, 0xf5, 0x05, 0x00, 0x00,
}
